REPLACE INTO sync_regimen (id, name, code, old_code, description, category_id, Active) VALUES
(1,	'AZT + 3TC + LPV/r',	'AF1E',	NULL,	'AZT + 3TC + LPV/r',	2,	'1'),
(2,	'AZT + 3TC + ATV/r',	'AF1F',	NULL,	'AZT + 3TC + ATV/r',	2,	'1'),
(3,	'AZT + 3TC + DTG',	'AS1C',	NULL,	'AZT + 3TC + DTG',	3,	'1'),
(4,	'TDF + 3TC + DTG',	'AS2B',	NULL,	'TDF + 3TC + DTG',	3,	'1'),
(5,	'ABC + 3TC + DTG',	'AS5C',	NULL,	'ABC + 3TC + DTG',	3,	'1'),
(6,	'TDF+3TC+DTG+DRV+RTV',	'AT2D',	NULL,	'TDF+3TC+DTG+DRV+RTV',	12,	'1'),
(7,	'TDF+3TC+RAL+DRV+RTV',	'AT2E',	NULL,	'TDF+3TC+RAL+DRV+RTV',	12,	'1'),
(8,	'TDF+3TC+DTG+ETV+DRV+RTV',	'AT2F',	NULL,	'TDF+3TC+DTG+ETV+DRV+RTV',	12,	'1'),
(9,	'1A Adult patients (=>15 Yrs) newly',	'ATPT',	NULL,	'1A Adult patients (=>15 Yrs) newly',	11,	'1'),
(10,	'1B Adult patients (=>15 Yrs) newly',	'ATPT',	NULL,	'1B Adult patients (=>15 Yrs) newly',	11,	'1'),
(11,	'ABC+3TC+DTG',	'CF2G',	NULL,	'ABC+3TC+DTG',	5,	'1'),
(12,	'AZT + 3TC + DRV+RTV+RAL',	'CS1C',	NULL,	'AZT + 3TC + DRV+RTV+RAL',	6,	'1'),
(13,	'ABC+3TC+DTG',	'CS2B',	NULL,	'ABC+3TC+DTG',	6,	'1'),
(14,	'ABC + 3TC + DRV+RTV+RAL',	'CS2D',	NULL,	'ABC + 3TC + DRV+RTV+RAL',	6,	'1'),
(15,	'AZT + 3TC + DRV+RTV+RAL',	'CT1H',	NULL,	'AZT + 3TC + DRV+RTV+RAL',	13,	'1'),
(16,	'ABC + 3TC + DRV+RTV+RAL',	'CT2D',	NULL,	'ABC + 3TC + DRV+RTV+RAL',	13,	'1'),
(17,	'1A Paed patients (<15 Yrs) newly s',	'CTPT',	NULL,	'1A Paed patients (<15 Yrs) newly s',	11,	'1'),
(18,	'1B Paed patients (<15 Yrs) newly s',	'CTPT',	NULL,	'1B Paed patients (<15 Yrs) newly s',	11,	'1'),
(19,	'Adult patients (=>15 Yrs) on Amph',	'OI6A',	NULL,	'Adult patients (=>15 Yrs) on Amph',	11,	'1'),
(20,	'TDF + 3TC + DTG (Adult PEP)',	'PA3D',	NULL,	'TDF + 3TC + DTG (Adult PEP)',	8,	'1'),
(21,	'ABC + 3TC + RAL (Paed PEP)',	'PC3B',	NULL,	'ABC + 3TC + RAL (Paed PEP)',	9,	'1'),
(22,	'PMTCT HAART: TDF + 3TC + DTG',	'PM12',	NULL,	'PMTCT HAART: TDF + 3TC + DTG',	1,	'1'),
(23,	'PMTCT HAART: AZT + 3TC + DTG',	'PM13',	NULL,	'PMTCT HAART: AZT + 3TC + DTG',	1,	'1'),
(24,	'PMTCT HAART: ABC + 3TC + DTG',	'PM14',	NULL,	'PMTCT HAART: ABC + 3TC + DTG',	1,	'1'),
(25,	'PMTCT HAART: ABC + 3TC + EFV',	'PM15',	NULL,	'PMTCT HAART: ABC + 3TC + EFV',	1,	'1')//